### ISSUE TITLE
맥북프로에 git config 변경해주세요.

### ISSUE THREAD

**Issue by afr5** [stayfoolish24/FirstTodo#2]
git commit 메시지가 SeoulStore로 찍히고 있고, 커밋잔디도 생성되지 않는데요. 
나중에 이직을 위해서라도 Github 계정을 관리하시는 걸 추천드립니다. 

```
$ git config --list
```
터미널에서 다음을 타이핑 해보시면 현재 컨피그가 어떻게 되어있는지 볼 수 있는데요. 
이 중에서 `user.name`은 본인의 이름을, `user.email`은 github 이메일로 설정해보세요. 

그러면 커밋할 때마다 github 프로필에 초록색 잔디가 생길 거에요. 
1일 1커밋으로 잔디밭 만드시면 이력서 관리하듯이 도움이 될 것 같아요.

**Comment by stayfoolish24** [comment]
[해결방법](https://afrobambacar.github.io/2017/05/common-reasons-that-contributions-are-not-counted.html)
